### ISSUE TITLE
按照你的示例效果不出来是怎么回事？

### ISSUE THREAD

**Issue by wangGuangXu** [zhaotianff/CSharpCrawler#2]
我把你的代码跑起来可以，我自己另外写一个程序，没法提取URL。你的邮箱地址多少？或者博客园地址是多少？能否跟您探讨一下

**Comment by zhaotianff** [comment]
未及时看到你提的issue，我的邮箱地址是keepoptimistic@myfreetime.cn，可以一起学习一下
